export enum TextTag {
    Span = "span",
    Paragraph = "p",
    Heading1 = "h1",
    Heading2 = "h2",
    Heading3 = "h3",
    Heading4 = "h4",
    Heading5 = "h5",
    Heading6 = "h6",
    Strong = "strong",
    Emphasis = "em",
    Label = "label",
    Small = "small",
    Div = "div",
}
